const $=id=>document.getElementById(id);
const SAVE='v5_save_v2';
let state={player:{hp:150,maxHp:150,mp:60,maxMp:60,atk:15,rage:0,lv:1,inventory:['potion_small'],equipment:{weapon:null,armor:null},loc:'ruin',clears:{wasteland:0,city:0}},enemy:null};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const bonus=(slot,stat)=>{const id=state.player.equipment[slot];return id&&items[id]&&items[id][stat]?items[id][stat]:0};
const maxHp=()=>state.player.maxHp+bonus('armor','hp');
const atk=()=>state.player.atk+bonus('weapon','atk');
function txt(id,v){const el=$(id);if(el)el.innerText=v;}
function html(id,v){const el=$(id);if(el)el.innerHTML=v;}
function show(id){const el=$(id);if(el)el.classList.remove('hidden');}
function hide(id){const el=$(id);if(el)el.classList.add('hidden');}
function msg(v){txt('system-message',v||'');}
function regionText(k){return storyData&&storyData[k]?storyData[k]:'你來到新的區域。';}
function ui(){const p=state.player;p.hp=clamp(p.hp,0,maxHp());p.mp=clamp(p.mp,0,p.maxMp);txt('hp-text',`${p.hp}/${maxHp()}`);txt('mp-text',`${p.mp}/${p.maxMp}`);txt('rage-text',`${p.rage}/100`);if($('hp-bar'))$('hp-bar').style.width=(p.hp/maxHp()*100)+'%';if($('mp-bar'))$('mp-bar').style.width=(p.mp/p.maxMp*100)+'%';if($('rage-bar'))$('rage-bar').style.width=p.rage+'%';html('stats',`<div>等級：${p.lv}</div><div>攻擊：${atk()}</div><div>位置：${mapData[p.loc]?.name||''}</div><div>荒原清除：${p.clears.wasteland}</div>`);html('equipment-panel',`<div class='equipment-item'>武器：${p.equipment.weapon&&items[p.equipment.weapon]?items[p.equipment.weapon].name:'無'}</div><div class='equipment-item'>防具：${p.equipment.armor&&items[p.equipment.armor]?items[p.equipment.armor].name:'無'}</div>`);}
function renderMap(){const el=$('map-panel');if(!el)return;el.innerHTML='';Object.keys(mapData).forEach(k=>{const n=mapData[k];const b=document.createElement('button');b.className='map-node'+(n.unlocked?'':' locked');b.disabled=!n.unlocked;b.innerText=n.name;b.onclick=()=>move(k);el.appendChild(b);});}
function renderInv(){const el=$('inventory-panel');if(!el)return;el.innerHTML='';state.player.inventory.forEach(id=>{const it=items[id];if(!it)return;const b=document.createElement('button');b.className='inventory-item'+(it.slot?' equip':'');b.innerText=it.name;b.onclick=()=>{if(it.type==='consumable')use(id);else equip(id)};el.appendChild(b);});}
function equip(id){const it=items[id];if(!it||!it.slot)return;state.player.equipment[it.slot]=id;msg('已裝備：'+it.name);renderAll();}
function use(id){const it=items[id];if(!it)return;if(it.effect?.hp)state.player.hp=clamp(state.player.hp+it.effect.hp,0,maxHp());const idx=state.player.inventory.indexOf(id);if(idx>=0)state.player.inventory.splice(idx,1);msg('已使用：'+it.name);renderAll();}
function randomSmallEnemy(region){if(region==='wasteland')return 'bandit';if(region==='city')return Math.random()<0.6?'ghost':'bandit';return null;}
function move(k){state.player.loc=k;let text='你移動到 '+mapData[k].name+'。\n'+regionText(k);if(k==='boss'){if(state.player.clears.wasteland<1||state.player.clears.city<1){text+='\n深淵核心被封鎖，你必須先擊敗荒原與古都的敵人。';txt('story',text);msg('Boss 尚未解鎖');renderAll();return;}txt('story',text+'\nBoss 現身：魔化將軍！');startBattle('boss');return;}const foe=randomSmallEnemy(k);txt('story',text+(foe?'\n你在此地遭遇敵人！':'\n此地暫時安全。'));if(foe)startBattle(foe);else{msg('已移動');renderAll();}}
function startBattle(type){const src=enemies[type];if(!src){msg('敵人資料缺失');return;}state.enemy={key:type,name:src.name,hp:src.hp,maxHp:src.hp,atk:src.atk,drop:src.drop||[]};show('battle-panel');renderBattle();}
function renderBattle(){const e=state.enemy;if(!e)return;txt('enemy-name',e.name);txt('enemy-level',e.key==='boss'?'Boss':'Lv.'+state.player.lv);txt('enemy-hp-text',`${e.hp}/${e.maxHp}`);if($('enemy-hp-bar'))$('enemy-hp-bar').style.width=(e.hp/e.maxHp*100)+'%';const box=$('battle-actions');if(!box)return;box.innerHTML='';[['普通攻擊',()=>turn('a')],['武君戰印',()=>turn('s')],['計略觀心',()=>turn('m')],['計都斬',()=>turn('u')]].forEach(([t,f])=>{const b=document.createElement('button');b.innerText=t;b.onclick=f;box.appendChild(b);});ui();}
function blog(v){txt('battle-log',v);}
function turn(t){const p=state.player,e=state.enemy;if(!e)return;let dmg=0,log='';if(t==='a'){dmg=Math.floor(atk()+Math.random()*6);p.rage=clamp(p.rage+20,0,100);log='你揮刀造成 '+dmg+' 傷害。';}if(t==='s'){if(p.mp<10){blog('真元不足。');return;}p.mp-=10;dmg=Math.floor(atk()+12+Math.random()*6);p.rage=clamp(p.rage+10,0,100);log='武君戰印造成 '+dmg+' 傷害。';}if(t==='m'){p.mp=clamp(p.mp+10,0,p.maxMp);blog('你恢復真元。');ui();return;}if(t==='u'){if(p.rage<100){blog('怒氣不足。');return;}p.rage=0;dmg=Math.floor(atk()+28+Math.random()*8);log='計都斬爆發，造成 '+dmg+' 傷害。';}e.hp-=dmg;if(e.hp<=0){winBattle(log);return;}const edmg=Math.floor(e.atk+Math.random()*5);p.hp=clamp(p.hp-edmg,0,maxHp());if(p.hp<=0){blog(log+'\n'+e.name+' 反擊 '+edmg+'，你戰敗了。');html('battle-actions','');msg('請讀檔或重新開始');ui();return;}blog(log+'\n'+e.name+' 反擊 '+edmg+'。');renderBattle();}
function maybeDrop(arr){if(!arr||!arr.length)return null;return Math.random()<0.8?arr[Math.floor(Math.random()*arr.length)]:null;}
function unlockFlow(){if(state.player.clears.wasteland>=1&&mapData.city)mapData.city.unlocked=true;if(state.player.clears.wasteland>=1&&state.player.clears.city>=1&&mapData.boss)mapData.boss.unlocked=true;}
function winBattle(prefix){const e=state.enemy;hide('battle-panel');html('battle-actions','');state.player.lv++;state.player.hp=clamp(state.player.hp+20,0,maxHp());state.player.mp=clamp(state.player.mp+8,0,state.player.maxMp);if(state.player.loc==='wasteland')state.player.clears.wasteland++;if(state.player.loc==='city')state.player.clears.city++;unlockFlow();const drop=maybeDrop(e.drop);let t=prefix+'\n你擊敗了 '+e.name+'。';if(drop&&items[drop]){state.player.inventory.push(drop);t+='\n獲得掉寶：'+items[drop].name+'。';msg('獲得：'+items[drop].name);}if(e.key==='boss'){t+='\n你擊敗了最終 Boss，完成了這段征途。';msg('Boss 已擊敗！');}txt('story',t);state.enemy=null;renderAll();}
function save(){localStorage.setItem(SAVE,JSON.stringify({state,mapData}));msg('已儲存進度');}
function load(){const raw=localStorage.getItem(SAVE);if(!raw){msg('沒有存檔');return;}const s=JSON.parse(raw);state=s.state||state;Object.assign(mapData,s.mapData||{});renderAll();txt('story',regionText(state.player.loc));msg('已讀取進度');}
function restart(){state={player:{hp:150,maxHp:150,mp:60,maxMp:60,atk:15,rage:0,lv:1,inventory:['potion_small'],equipment:{weapon:null,armor:null},loc:'ruin',clears:{wasteland:0,city:0}},enemy:null};if(mapData.wasteland)mapData.wasteland.unlocked=true;if(mapData.city)mapData.city.unlocked=false;if(mapData.boss)mapData.boss.unlocked=false;hide('battle-panel');txt('story',regionText('ruin'));renderAll();msg('已重新開始');}
function renderAll(){ui();renderMap();renderInv();}
function start(){hide('title-screen');show('game-app');if(mapData.wasteland)mapData.wasteland.unlocked=true;txt('story',regionText('ruin')+'\n請點擊地圖移動。');renderAll();msg('遊戲開始');}
function bind(){if($('start-game-btn'))$('start-game-btn').onclick=start;if($('show-help-btn'))$('show-help-btn').onclick=()=>show('help-modal');if($('close-help-btn'))$('close-help-btn').onclick=()=>hide('help-modal');if($('save-btn'))$('save-btn').onclick=save;if($('load-btn'))$('load-btn').onclick=load;if($('restart-btn'))$('restart-btn').onclick=restart;}
function show(id){const el=$(id);if(el)el.classList.remove('hidden')}
function hide(id){const el=$(id);if(el)el.classList.add('hidden')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();