const LIVE_SAVE='v4_fixed_live';
const $=id=>document.getElementById(id);
let state={player:{hp:150,maxHp:150,mp:60,maxMp:60,rage:0,atk:15,lv:1,inventory:['potion_small','blade_jidu'],equipment:{weapon:null,armor:null,accessory:null},location:'ruin'},enemy:null};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const bonus=(slot,stat)=>{const id=state.player.equipment[slot];return id&&items[id]&&items[id][stat]?items[id][stat]:0};
const maxHp=()=>state.player.maxHp+bonus('armor','hp');
const maxMp=()=>state.player.maxMp+bonus('accessory','mp');
const atk=()=>state.player.atk+bonus('weapon','atk');
function txt(id,v){const el=$(id); if(el) el.innerText=v;}
function html(id,v){const el=$(id); if(el) el.innerHTML=v;}
function show(id){const el=$(id); if(el) el.classList.remove('hidden');}
function hide(id){const el=$(id); if(el) el.classList.add('hidden');}
function msg(v){txt('system-message',v||'');}
function renderStatus(){const p=state.player;p.hp=clamp(p.hp,0,maxHp());p.mp=clamp(p.mp,0,maxMp());txt('hp-text',`${p.hp}/${maxHp()}`);txt('mp-text',`${p.mp}/${maxMp()}`);txt('rage-text',`${p.rage}/100`);if($('hp-bar'))$('hp-bar').style.width=(p.hp/maxHp()*100)+'%';if($('mp-bar'))$('mp-bar').style.width=(p.mp/maxMp()*100)+'%';if($('rage-bar'))$('rage-bar').style.width=p.rage+'%';html('stats',`<div>等級：${p.lv}</div><div>攻擊：${atk()}</div><div>位置：${mapData[p.location]?.name||''}</div><div>狀態：${p.hp>0?'可戰':'倒下'}</div>`);html('equipment-panel',`<div class='equipment-item'>武器：${p.equipment.weapon?items[p.equipment.weapon].name:'無'}</div><div class='equipment-item'>防具：${p.equipment.armor?items[p.equipment.armor].name:'無'}</div><div class='equipment-item'>飾品：${p.equipment.accessory?items[p.equipment.accessory].name:'無'}</div>`)}
function renderStory(v){txt('story',v||'');}
function renderMap(){const el=$('map-panel'); if(!el) return; el.innerHTML=''; Object.keys(mapData).forEach(k=>{const n=mapData[k];const d=document.createElement('button');d.className='map-node'+(n.unlocked?'':' locked');d.disabled=!n.unlocked;d.innerText=n.name;d.onclick=()=>enterMap(k);el.appendChild(d);});}
function renderInventory(){const el=$('inventory-panel'); if(!el) return; el.innerHTML=''; state.player.inventory.forEach(id=>{const it=items[id]; if(!it) return; const b=document.createElement('button'); b.className='inventory-item'; b.innerText=it.name; b.onclick=()=>{if(it.type==='consumable') useItem(id); else equipItem(id);}; el.appendChild(b);});}
function equipItem(id){const it=items[id]; if(!it||!it.slot) return; state.player.equipment[it.slot]=id; msg('已裝備：'+it.name); renderAll();}
function useItem(id){const it=items[id]; if(!it) return; if(it.effect?.hp) state.player.hp=clamp(state.player.hp+it.effect.hp,0,maxHp()); if(it.effect?.mp) state.player.mp=clamp(state.player.mp+it.effect.mp,0,maxMp()); const idx=state.player.inventory.indexOf(id); if(idx>=0) state.player.inventory.splice(idx,1); msg('已使用：'+it.name); renderAll();}
function enterMap(k){state.player.location=k; const node=mapData[k]; renderStory('你來到：'+node.name); msg('探索中…'); if(node.battle) startBattle(node.battle); else renderAll();}
function startBattle(key){if(!enemies[key]){msg('敵人資料缺失'); return;} state.enemy={...enemies[key],currentHp:enemies[key].hp}; show('battle-panel'); renderBattle();}
function renderBattle(){const e=state.enemy;if(!e)return; txt('enemy-name',e.name); txt('enemy-level','Lv.'+e.level); txt('enemy-hp-text',`${e.currentHp}/${e.hp}`); if($('enemy-hp-bar'))$('enemy-hp-bar').style.width=(e.currentHp/e.hp*100)+'%'; const box=$('battle-actions'); if(!box)return; box.innerHTML=''; [['普通攻擊',()=>takeTurn('a')],['武君戰印',()=>takeTurn('s')],['計略觀心',()=>takeTurn('m')],['終式・計都斬',()=>takeTurn('u')]].forEach(([t,f])=>{const b=document.createElement('button');b.innerText=t;b.onclick=f;box.appendChild(b);}); renderStatus();}
function battleLog(v){txt('battle-log',v);}
function takeTurn(type){const p=state.player,e=state.enemy;if(!e)return;let dmg=0,log='';if(type==='a'){dmg=Math.floor(atk()+Math.random()*6);p.rage=clamp(p.rage+20,0,100);log='你攻擊造成 '+dmg+' 傷害。';}if(type==='s'){if(p.mp<10){battleLog('真元不足。');return;}p.mp-=10;dmg=Math.floor(atk()+15);p.rage=clamp(p.rage+10,0,100);log='武君戰印造成 '+dmg+' 傷害。';}if(type==='m'){p.mp=clamp(p.mp+10,0,maxMp());log='你恢復了真元。';}if(type==='u'){if(p.rage<100){battleLog('怒氣不足。');return;}p.rage=0;dmg=Math.floor(atk()+35);log='終式造成 '+dmg+' 傷害。';}e.currentHp-=dmg;if(e.currentHp<=0){winBattle(log);return;}const edmg=Math.floor(e.atk+Math.random()*4);p.hp=clamp(p.hp-edmg,0,maxHp());if(p.hp<=0){battleLog(log+'\n'+e.name+' 反擊 '+edmg+'，你戰敗了。');html('battle-actions','');msg('請重新開始或讀檔');renderStatus();return;}battleLog(log+'\n'+e.name+' 反擊 '+edmg+'。');renderBattle();}
function winBattle(prefix){const e=state.enemy;hide('battle-panel');html('battle-actions','');state.player.lv+=1;state.player.hp=clamp(state.player.hp+20,0,maxHp());state.player.mp=clamp(state.player.mp+10,0,maxMp());if(e.drop&&e.drop[0]&&items[e.drop[0]]){state.player.inventory.push(e.drop[0]);msg('獲得：'+items[e.drop[0]].name);}if(state.player.location==='ruin'&&mapData.wasteland)mapData.wasteland.unlocked=true;if(state.player.location==='wasteland'&&mapData.ghost_city)mapData.ghost_city.unlocked=true;state.enemy=null;renderStory(prefix+'\n戰鬥勝利。');renderAll();}
function save(){localStorage.setItem(LIVE_SAVE,JSON.stringify({state,mapData}));msg('已儲存');}
function load(){const raw=localStorage.getItem(LIVE_SAVE);if(!raw){msg('沒有存檔');return;}const s=JSON.parse(raw);state=s.state||state;Object.assign(mapData,s.mapData||{});renderAll();msg('已讀檔');}
function restart(){state={player:{hp:150,maxHp:150,mp:60,maxMp:60,rage:0,atk:15,lv:1,inventory:['potion_small','blade_jidu'],equipment:{weapon:null,armor:null,accessory:null},location:'ruin'},enemy:null};if(mapData.wasteland)mapData.wasteland.unlocked=false;if(mapData.ghost_city)mapData.ghost_city.unlocked=false;hide('battle-panel');renderStory('你從天都廢墟醒來。');renderAll();msg('已重新開始');}
function renderAll(){renderStatus();renderMap();renderInventory();}
function startGame(){hide('title-screen');show('game-app');renderStory('你從天都廢墟醒來。請點選地圖開始探索。');renderAll();msg('遊戲開始');}
function bind(){if($('start-game-btn'))$('start-game-btn').onclick=startGame;if($('show-help-btn'))$('show-help-btn').onclick=()=>show('help-modal');if($('close-help-btn'))$('close-help-btn').onclick=()=>hide('help-modal');if($('save-btn'))$('save-btn').onclick=save;if($('load-btn'))$('load-btn').onclick=load;if($('restart-btn'))$('restart-btn').onclick=restart;if($('toggle-audio-btn'))$('toggle-audio-btn').onclick=()=>msg('音效功能預留');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();